export const SET_TVSHOWS = 'SET_TVSHOWS';
export const FETCH_TVSHOWS_FAILED = 'FETCH_TVSHOWS_FAILED';
export const FETCH_TVSHOWS_STARTED = 'FETCH_TVSHOWS_STARTED';

export const SET_EPISODES = 'SET_EPISODES';
export const FETCH_EPISODES_STARTED = 'FETCH_EPISODES_STARTED';
export const FETCH_EPISODES_FAILED = 'FETCH_EPISODES_FAILED';
export const SET_ISLOADING = 'SET_ISLOADING';
export const SET_NOT_ISLOADING = 'SET_NOT_ISLOADING';