export const SET_TVSHOWS_SAGA = 'SET_TVSHOWS_SAGA';
export const SET_TVSHOWS = 'SET_TVSHOWS';
export const FETCH_TVSHOWS_FAILED = 'FETCH_TVSHOWS_FAILED';
export const FETCH_TVSHOWS_STARTED = 'FETCH_TVSHOWS_STARTED';

export const INIT_EPISODES_SAGA = 'INIT_EPISODES_SAGA'
export const SET_EPISODES = 'SET_EPISODES';
export const FETCH_EPISODES_STARTED = 'FETCH_EPISODES_STARTED';
export const FETCH_EPISODES_FAILED = 'FETCH_EPISODES_FAILED';
export const SET_ISLOADING = 'SET_ISLOADING';
export const SET_NOT_ISLOADING = 'SET_NOT_ISLOADING';

export const SUBMIT_TVSHOW_SAGA = 'SUBMIT_TVSHOW_SAGA';
export const SUBMIT_TVSHOW = 'SUBMIT_TVSHOW';
export const SUBMIT_TVSHOW_STARTED = 'SUBMIT_TVSHOW_STARTED';
export const SUBMIT_TVSHOW_FAILED = 'SUBMIT_TVSHOW_FAILED';

export const DELETE_TVSHOW_SAGA = 'DELETE_TVSHOW_SAGA';
export const DELETE_TVSHOW = 'DELETE_TVSHOW';
export const DELETE_TVSHOW_STARTED = 'DELETE_TVSHOW_STARTED';
export const DELETE_TVSHOW_FAILED = 'DELETE_TVSHOW_FAILED';